---
minimum_pre_commit_version: 3.7.0

repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.21.3
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
# Black (uncompromising) Python code formatter
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
    args:
    - --target-version
    - py312
# MyPy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    files: ^workflow
    args:
    - --install-types
    - --non-interactive
# YAML Lint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
# Pylint
- repo: https://github.com/pycqa/pylint
  rev: v3.1.0
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    additional_dependencies:
    - jinja2==3.0.3
    - jsonschema >= 3.2.0, < 4.0
    - pyyaml >= 5.3.1, < 7.0
    files: ^workflow/.*\.py$